### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by shun1131** [Rev-Tech/card-wallet#21]
・デザインイメージが届き次第作業開始

**Comment by shun1131** [comment]
ハイ君作業中

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/pull/32

**Comment by shun1131** [comment]
【サインインページ】
・背景の画像を変更
・下の画像の通り表記を変更
・サインアップのURLを表示させた時、サインインの内容が表示されてしまうので、サインアップの入力画面が表示されるようにする。

<img width="1438" alt="スクリーンショット_2019-12-09_12_55_58" src="https://user-images.githubusercontent.com/3445358/70406674-e8164400-1a84-11ea-8911-8bb0958ba81e.png">


[背景の画像]
![1_vHGt8NssypPbrkeCTXF5Lg](https://user-images.githubusercontent.com/3445358/70406725-03814f00-1a85-11ea-9c57-16cfda2956b2.png)

**Comment by shun1131** [comment]
【サイドバー】
・枠のところのアイコンが表示されていない

<img width="247" alt="スクリーンショット_2019-12-09_13_09_50" src="https://user-images.githubusercontent.com/3445358/70406844-5c50e780-1a85-11ea-8b2d-fc18fbc37fae.png">

**Comment by shun1131** [comment]
【プロフィール画面】
・二段階認証の項目がプロフィール変更の上に来てないので変更

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/issues/41
