### ISSUE TITLE
追加購入画面の表記追加

### ISSUE THREAD

**Issue by shun1131** [Rev-Tech/card-wallet#35]
・追加購入画面の隣にAdditional Pointを追加、単位はいらない

<img width="1120" alt="スクリーンショット_2019-12-04_14_33_06" src="https://user-images.githubusercontent.com/3445358/70117260-57b4b980-16a8-11ea-94f3-e4d510e7ce79.png">

※レートはUSDと同じなので、表示させる数値はUSD amountと同じでOK

**Comment by shun1131** [comment]
購入の際の規約に同意するチェックボタンは削除
（※初回購入のページも同じように）

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/pull/47
