### ISSUE TITLE
アカウントの表示方法の修正

### ISSUE THREAD

**Issue by shun1131** [Rev-Tech/card-wallet#37]
(PC)
<img width="1002" alt="スクリーンショット_2019-12-04_16_49_33" src="https://user-images.githubusercontent.com/3445358/70124197-900fc400-16b7-11ea-83d1-289a65e6a13b.png">

(Mobile)
<img width="311" alt="スクリーンショット_2019-12-04_16_49_00" src="https://user-images.githubusercontent.com/3445358/70124213-97cf6880-16b7-11ea-9557-2dee00d389d4.png">

**Comment by shun1131** [comment]
※B21トークンのUSDTconversion表示はいらないのでついでに削除

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/issues/41
