### ISSUE TITLE
サイドバーに項目追加

### ISSUE THREAD

**Issue by shun1131** [Rev-Tech/card-wallet#38]
<img width="748" alt="スクリーンショット_2019-12-04_17_15_41" src="https://user-images.githubusercontent.com/3445358/70125315-f39af100-16b9-11ea-871a-48bc5f6171b6.png">

・枠で囲んでいる項目をユーザのnicknameの下に追加
・追加する項目は3つ
・左から「マイページへ移動」「メーラー起動」「サインアウト」の処理がクリックしたときにされるようにする

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/issues/41
