### ISSUE TITLE
プロフィール画面の変更

### ISSUE THREAD

**Issue by shun1131** [Rev-Tech/card-wallet#41]
・「変更」ボタンを設置して、クリックすると赤の枠で囲んでいる内容がモーダル表示されるようにする。

<img width="1133" alt="スクリーンショット_2019-12-05_14_25_19" src="https://user-images.githubusercontent.com/3445358/70206838-200f4580-176c-11ea-839f-8a87b3282bdb.png">

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/issues/21

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/issues/21

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/issues/39

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/pull/43
