### ISSUE TITLE
二段階認証の設定箇所を変更

### ISSUE THREAD

**Issue by shun1131** [Rev-Tech/card-wallet#42]
マイページの二段階認証の項目をページの一番上(change profileの上)に表示させる。

<img width="313" alt="スクリーンショット_2019-12-05_14_34_53" src="https://user-images.githubusercontent.com/3445358/70207022-c65b4b00-176c-11ea-87c2-af24d2a60c0e.png">

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/issues/21
