### ISSUE TITLE
マップデザインの変更

### ISSUE THREAD

**Issue by shun1131** [Rev-Tech/card-wallet#44]
http://localhost:3000/ja/wallet/uni_level/index

①、
・このページに表示されているマップの見た目を変える。
（※イメージ）
![map](https://user-images.githubusercontent.com/3445358/70497742-81158f80-1b57-11ea-85d8-1bf4a9a705a2.gif)
（線と四角が角ばってる感じで）

②、
招待URLを一番上に表示させる。
（※ハーベストプログラムの上）

③、
名前の変更
「ハーベストプログラム」
↓
「ユニマップ」

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/pull/47
