### ISSUE TITLE
パスワード入力画面に説明文の追加

### ISSUE THREAD

**Issue by shun1131** [Rev-Tech/card-wallet#46]
・「大文字最低1文字以上、小文字裁定1文字以上、数字最低1文字以上の12文字以上を入力してください」

<img width="884" alt="スクリーンショット_2019-12-11_17_22_03" src="https://user-images.githubusercontent.com/3445358/70604066-438a3280-1c3b-11ea-981f-0d7fb29ca4e4.png">

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/pull/47
