### ISSUE TITLE
購入画面にカードのサービス内容のテーブル表示を追加

### ISSUE THREAD

**Issue by shun1131** [Rev-Tech/card-wallet#48]
(※サンプルイメージ)
![photo_2019-12-11_19-15-31](https://user-images.githubusercontent.com/3445358/70612676-b5b64380-1c4a-11ea-9df8-3e77b3a0b2ae.jpg)

・初回購入画面と追加購入画面の両方に表示

**Comment by shun1131** [comment]
(※実際に載せたい内容のイメージ)

![photo_2019-12-11_19-15-31 2](https://user-images.githubusercontent.com/3445358/70614828-98837400-1c4e-11ea-82e8-4f0f9fa35406.jpg)

**Comment by pnghai** [comment]
https://github.com/Rev-Tech/card-wallet/pull/50
