### ISSUE TITLE
Add Curency(Deposit and withdraw)

### ISSUE THREAD

**Issue by ryotakataoka** [Rev-Tech/card-wallet#86]
【Target place · file】
https://club21.io/en/wallet/deposit
https://club21.io/en/wallet/remittance

we don't need this screen.
Withdraw:https://drive.google.com/file/d/1Z6kwm_RhKnYt6LzGbEXLh8T8CZT5DQZd/view?usp=sharing
Deposit:https://drive.google.com/file/d/1zPTe0fI1hF7aOC_-ag82tfQvXyOxkABi/view?usp=sharing

please choose able with select currency with tab
image:https://drive.google.com/file/d/1Bp2UzJ86XhayIX8rhpPO7L-4c3DrAwRO/view?usp=sharing
same as revollet

【Additional Functions】
Add 
XRP
ETH
USDC
USDT
【Description】
Minimum Withdraw amount
XRP 0.2
ETH 0.006
USDC 15
USDT 15

【Corrected Results】

【important point】

【Other reference】

**Comment by kaizvn** [comment]
PR : #101
